sudo: required

language: bash

before_install:
  - sudo apt update
  - sudo apt-get update -q
  - export scversion="stable" # or "v0.4.7", or "latest"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
  - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
  - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
  - /usr/bin/shellcheck --version

  - sudo apt install -y imagemagick ghostscript p7zip-full
  - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/worldcupplayerinfo.tsv"
  - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
  - 7z x web_log.tsv.7z

script:
  - ls -l
    # - bash chap0x04/Codes/gcd.sh
  - printf "=============== Task1===============\n"
  - bash chap0x04/Codes/image-batching.sh -h
  - bash chap0x04/Codes/image-batching.sh -d chap0x04/images/ -q 50%
  - bash chap0x04/Codes/image-batching.sh -d chap0x04/images/ -r 90
  - bash chap0x04/Codes/image-batching.sh -d chap0x04/images/ -w "www.cnblogs.com"
  - bash chap0x04/Codes/image-batching.sh -d chap0x04/images/ -p "Pre"
  - bash chap0x04/Codes/image-batching.sh -d chap0x04/images/ -s "Tail"
  - bash chap0x04/Codes/image-batching.sh -d chap0x04/images/ -c
  - printf "=============== Task2===============\n"
  - bash chap0x04/Codes/player-data.sh -h
  - bash chap0x04/Codes/player-data.sh -ar 
  - bash chap0x04/Codes/player-data.sh -p
  - bash chap0x04/Codes/player-data.sh -n 
  - bash chap0x04/Codes/player-data.sh -ac 
  - printf "=============== Task3===============\n"
  - bash chap0x04/Codes/weblog.sh -h
  - bash chap0x04/Codes/weblog.sh -o 100
  - bash chap0x04/Codes/weblog.sh -i 100
  - bash chap0x04/Codes/weblog.sh -u 100
  - bash chap0x04/Codes/weblog.sh -r
  - bash chap0x04/Codes/weblog.sh -u4 100
  - bash chap0x04/Codes/weblog.sh -uh  "/images/KSC-logosmall.gif" 100
  - ls -l

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
